### ISSUE TITLE
Consume events from Event Streams

### ISSUE THREAD

**Issue by yeekangc** [IBMStockTrader/trade-history#2]
Develop a consumer that will consume events for the stocktrader topic produced by the portfolio service from Event Streams.

Events will be JSON representation of https://github.com/IBMStockTrader/portfolio/blob/master/src/main/java/com/ibm/hybrid/cloud/sample/stocktrader/portfolio/json/StockPurchase.java

@jjvilleg @kevinwlau

**Comment by yeekangc** [comment]
#6

**Comment by kevinwlau** [comment]
This work is done. The trade-history app is able to consume successfully if the secrets are in place to connect to the Event Stream.
